// Hockey — NHL: gated (Step 10.2, option 2).
//
// This vertical shipped with fabricated data and is now an honest parked
// state. The route and nav entry stay; the fabrication is deleted.
//
// Exactly what was fabricated and removed:
// - src/pages/hockey/teamStats.ts — EVERY NHL team line: GF, GA, xGF%, PP%,
//   PK% for the season and all four rolling windows, last-10 results,
//   home/away splits, the pace lean and the 1–32 strength rank. All of it
//   came from mulberry32(hash(abbr)) — a seeded PRNG, no source.
// - src/pages/hockey/extras.tsx — goalie home/away/vs-top-10 SV% splits and
//   skater home/away SOG splits from the same kind of seeded stream, and
//   line/PP deployment chips assigned by array index.
// - The goalie/skater "edge" scores blended the hydrated windows with those
//   invented splits.
//
// What is real and stays: src/data/nhlPlayers.ts is a live-data module
// (hydrated from players.goalies / players.skaters via the MySQL loader) and
// api/ingest/nhl.ts is the reference implementation for the em-dash rule.
// The loader path is currently blocked on DATABASE_URL, so even the real
// tables have nothing to render tonight.
//
// Unparking means wiring api/ingest/nhl.ts through the loader and rebuilding
// these screens on it — real work on a parked vertical, and it is Oakley's
// call, not something to half-do in the meantime.

import { motion } from 'framer-motion'
import { Construction } from 'lucide-react'

const FABRICATED = [
  'Every NHL team line (GF, GA, xGF%, PP%, PK%) for the season and all four rolling windows, plus last-10 results, home/away splits, pace lean and the strength rank — all generated by a seeded PRNG keyed on the team abbreviation',
  'Goalie home/away/vs-top-10 SV% splits and skater home/away SOG splits — seeded pseudo-random streams, no source',
  'Line and power-play deployment chips — assigned by array index, not by any roster feed',
  'Goalie and skater edge scores — formulas blended over the above',
]

const REAL_BUT_UNWIRED = [
  'src/data/nhlPlayers.ts hydrates from players.goalies / players.skaters (MySQL loader, currently blocked on DATABASE_URL)',
  'api/ingest/nhl.ts is the reference implementation for honest NHL ingest when this vertical is unparked',
]

export default function HockeyDashboard() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
      className="prizm-card p-8"
    >
      <div className="mb-4 flex items-center gap-3">
        <Construction size={20} strokeWidth={1.5} className="text-sp-amber" />
        <h3 className="font-display text-lg font-semibold text-text-1">Hockey — NHL</h3>
        <span className="data-mono rounded-sm border border-sp-amber/40 bg-sp-amber/10 px-1.5 py-px text-[10px] font-bold uppercase tracking-widest text-sp-amber">
          Parked
        </span>
      </div>

      <p className="mb-6 max-w-2xl text-sm leading-relaxed text-text-2">
        This vertical previously rendered fabricated statistics and has been taken down rather than
        left plausible-looking. Nothing on the old screen came from a data feed. It returns when the
        real ingest path is wired — that is a deliberate piece of work, not a gap to paper over.
      </p>

      <p className="overline-caption mb-2 text-text-3">What was fabricated and removed</p>
      <ul className="mb-6 space-y-1.5">
        {FABRICATED.map((f) => (
          <li key={f} className="flex gap-2 text-[13px] text-text-3">
            <span aria-hidden className="text-text-3">
              —
            </span>
            <span>{f}</span>
          </li>
        ))}
      </ul>

      <p className="overline-caption mb-2 text-text-3">Real, but not wired yet</p>
      <ul className="space-y-1.5">
        {REAL_BUT_UNWIRED.map((r) => (
          <li key={r} className="flex gap-2 text-[13px] text-text-2">
            <span aria-hidden className="text-success">
              ✓
            </span>
            <span>{r}</span>
          </li>
        ))}
      </ul>
    </motion.div>
  )
}
